### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by manikumaran1978** [magesuite/pwa#2]
composer require creativestyle/magesuite-pwa --no-update

[InvalidArgumentException]
  Could not find a version of package creativestyle/magesuite-pwa matching your minimum-stability (stable). Require it with an explicit version constraint
   allowing its desired stability.

**Comment by ggm-dev** [comment]
Hi All - I was able to install PWA and PWA-notifications on 2.4.0 with magesuite 6 by setting min-stability to "dev".  

Modules have installed correctly, are enabled and I even see Notifications tab available in customer account of frontend, however I don't see service-worker.js or manifest.json loading on frontend.  Are there any other config settings that I need to be aware of or extra steps?

Thanks so much!

**Comment by diwipl** [comment]
Hi,
PWA extensions are not yet in stable state. 
The only way to install them is to lower minimum-stability.
